# Generated by Django 5.2.1 on 2025-05-15 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0002_initial'),
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_meals', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='mealserving',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='meals.meal'),
        ),
        migrations.AddField(
            model_name='mealserving',
            name='served_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mealingredient',
            unique_together={('meal', 'ingredient')},
        ),
    ]
