# Generated by Django 5.2.1 on 2025-05-31 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('action_type', models.CharField(blank=True, choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SERVE', 'Serve'), ('ADD_QUANTITY', 'Add Quantity'), ('USE_QUANTITY', 'Use Quantity')], max_length=20, null=True)),
                ('model_type', models.CharField(blank=True, choices=[('ingredient', 'Ingredient'), ('meal', 'Meal'), ('meal_ingredient', 'Meal Ingredient'), ('meal_serving', 'Meal Serving'), ('ingredient_delivery', 'Ingredient Delivery'), ('ingredient_usage', 'Ingredient Usage')], max_length=30, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
