# Generated by Django 5.2.1 on 2025-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_meals_served', models.PositiveIntegerField(default=0)),
                ('total_servings', models.PositiveIntegerField(default=0)),
                ('total_potential_servings', models.PositiveIntegerField(default=0)),
                ('discrepancy_rate', models.FloatField(default=0.0, help_text='Discrepancy rate in percentage')),
                ('total_ingredients_used', models.PositiveIntegerField(default=0, help_text='Total ingredients used in grams')),
                ('total_ingredients_delivered', models.PositiveIntegerField(default=0, help_text='Total ingredients delivered in grams')),
                ('high_discrepancy', models.BooleanField(default=False, help_text='Flag if discrepancy rate exceeds threshold')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ReportIngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('quantity_used', models.PositiveIntegerField(default=0, help_text='Quantity used in grams')),
                ('quantity_delivered', models.PositiveIntegerField(default=0, help_text='Quantity delivered in grams')),
                ('discrepancy', models.IntegerField(default=0, help_text='Discrepancy in grams')),
            ],
            options={
                'ordering': ['-quantity_used'],
            },
        ),
        migrations.CreateModel(
            name='ReportMealServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('servings_count', models.PositiveIntegerField(default=0)),
                ('total_ingredients_used', models.PositiveIntegerField(default=0, help_text='Total ingredients used in grams')),
            ],
            options={
                'ordering': ['-servings_count'],
            },
        ),
    ]
