# Generated by Django 5.2.1 on 2025-05-15 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportingredientusage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_usages', to='reports.monthlyreport'),
        ),
        migrations.AddField(
            model_name='reportmealserving',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_servings', to='reports.monthlyreport'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('year', 'month')},
        ),
    ]
