name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_DB: kindergarten_db
                    POSTGRES_USER: admin_user
                    POSTGRES_PASSWORD: 1234
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        env:
            SECRET_KEY: 8d0a9720d39fca97713ca8aa474e1a0ccfbfdffe3ed02bd11b1070fccf4f54cc
            DEBUG: True
            DB_NAME: kindergarten_db
            DB_USER: admin_user
            DB_PASSWORD: 1234
            DB_HOST: localhost
            DB_PORT: 5432
            REDIS_HOST: redis://localhost
            REDIS_PORT: 6379
            CELERY_BROKER_URL: redis://localhost:6379/0
            CELERY_RESULT_BACKEND: redis://localhost:6379/0
            CORS_ALLOWED_ORIGINS: http://localhost:8000,http://127.0.0.1:8000
            DJANGO_SUPERUSER_USERNAME: admin
            DJANGO_SUPERUSER_EMAIL: admin@example.com
            DJANGO_SUPERUSER_PASSWORD: admin

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run tests
              run: |
                  python manage.py test
